# Generated by Django 5.2.5 on 2025-08-25 11:57

import django.db.models.deletion
import nazala_backend_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazala_backend_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_turns', models.IntegerField(default=12)),
                ('status', models.IntegerField(default=0)),
                ('join_token', models.CharField(max_length=64, unique=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_number', models.IntegerField()),
                ('text', models.TextField()),
                ('attr_a', models.IntegerField()),
                ('attr_b', models.IntegerField()),
                ('attr_c', models.IntegerField()),
                ('attr_d', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auth_token', models.CharField(db_index=True, default=nazala_backend_api.models._generate_token, max_length=128, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='nazala_backend_api.game')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('question_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='nazala_backend_api.game')),
            ],
            options={
                'unique_together': {('game', 'index')},
            },
        ),
        migrations.CreateModel(
            name='TurnSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_a', models.IntegerField()),
                ('attr_b', models.IntegerField()),
                ('attr_c', models.IntegerField()),
                ('attr_d', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turn', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='nazala_backend_api.turn')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='choice',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='nazala_backend_api.option'),
        ),
        migrations.AddField(
            model_name='choice',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='nazala_backend_api.player'),
        ),
        migrations.AddField(
            model_name='option',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='nazala_backend_api.turn'),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('option', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('turn', 'display_number')},
        ),
    ]
