# Generated by Django 5.2.5 on 2025-08-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazala_backend_api', '0002_choice_game_option_player_turn_turnsnapshot_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='turn',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('player', 'option'), name='unique_choice_per_turn_of_player'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(fields=('turn', 'display_number'), name='unique_option_per_turn'),
        ),
        migrations.AddConstraint(
            model_name='turn',
            constraint=models.UniqueConstraint(fields=('game', 'index'), name='unique_turn_index'),
        ),
    ]
